#!/usr/bin/env python
"""T3 - why the direction error sits at 5.71 degrees, and what the gate should be.

    python scripts/analyse_lateral_authority.py --seeds 0..11 --out docs/results/t3

The debt
--------
`docs/CLOSED_LOOP_D.md` records the identity

    max cross-track  =  J * sin(direction error),     correlation 0.968

so the G500 gate ``cross_track_max <= 0.15 m`` at ``J ~ 1.5 m`` *is* the requirement
"hold the net force direction to within 5.74 degrees for the whole push". The measured
mean direction error after the PD steering law is 5.71 degrees. The loop is sitting
exactly on its own requirement, and the brief asks for either a mechanism that raises
lateral authority -- not a higher gain -- or a gate restated on the reachable normal
cone, with a derivation.

The derivation
--------------
Each pushing robot presses along its own observed inward normal, so the net contact
force available to the team is

    F  =  sum_k  a_k (-n_k),      a_k in [0, a_max]

with ``k`` ranging over the push set. The coefficients are *nonnegative* -- a robot can
press or not press, it cannot pull -- so the set of achievable force directions is the
convex cone generated by ``{-n_k}``, and the achievable directions are exactly the
convex hull of those directions. Writing ``phi_k`` for the angle from the task direction
``d_goal`` to ``-n_k``, the reachable direction interval is

    Phi  =  [ min_k phi_k ,  max_k phi_k ]

and the team can aim anywhere in ``Phi`` and nowhere outside it, whatever the gain.

Two consequences follow immediately, and they are the answer to the debt:

1. **On a planar face the reachable cone is a single ray.** Every robot on one flat face
   observes the *same* normal, so all ``phi_k`` coincide, ``Phi`` collapses to a point,
   and the lateral authority is exactly zero. No allocation of effort among robots on a
   flat face can change the direction of the net force -- only its magnitude. Steering
   authority exists only where the arc straddles a corner onto a face with a different
   normal.

2. **The achievable direction error is therefore a property of the object's faceting and
   of where the arc happens to sit, not of the controller's gain.** Raising the gain
   cannot leave ``Phi``; that is why concentrating the effort allocation further was
   measured on the v1 branch and made things worse.

So the honest gate is not an absolute cross-track distance. It is

    cross-track  <=  J * sin( dist(d_goal, Phi) + resolution )

where ``dist(d_goal, Phi)`` is zero when the goal direction is inside the reachable cone
and the angular shortfall otherwise. This script measures ``Phi`` per frame over the
transport phase and reports what that gate would have been on each of the twelve seeds.

Everything measured here is read from the robots' own maps. The truth-side quantities
(the object's displacement, the achieved direction error) are used only to score.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from dbact.phase import Phase  # noqa: E402
from dbact_sim.environment import SimulationEnvironment  # noqa: E402
from dbact_sim.scenarios import load_yaml  # noqa: E402

BASE_CONFIG = "configs/sim/d/l_shape_closed_loop.yaml"
CROSS_TRACK_GATE = 0.15


def parse_seeds(spec: str) -> list[int]:
    if ".." in spec:
        low, high = (int(p) for p in spec.split("..", 1))
        return list(range(low, high + 1))
    return [int(p) for p in spec.split(",") if p.strip()]


def signed_angle(reference: np.ndarray, vector: np.ndarray) -> float:
    """Signed angle from ``reference`` to ``vector``, in degrees, in (-180, 180]."""
    cross = float(reference[0] * vector[1] - reference[1] * vector[0])
    dot = float(np.dot(reference, vector))
    return math.degrees(math.atan2(cross, dot))


def reachable_cone(normals: np.ndarray, goal: np.ndarray) -> dict:
    """The interval of net-force directions a nonnegative allocation can produce.

    ``normals`` are the *observed outward* normals of the robots in the push set, so the
    press directions are ``-n_k``. Because the coefficients are nonnegative the
    achievable set is their convex hull, which in the plane is the angular interval
    spanned by the extreme members -- provided that span is under 180 degrees, which the
    push-set membership test guarantees: every member satisfies ``n_k . d_goal <= -0.35``,
    so every ``-n_k`` lies within 69.5 degrees of ``d_goal`` and the whole set spans at
    most 139 degrees.
    """
    if len(normals) == 0:
        return {"members": 0, "distinct": 0, "half_width_deg": 0.0, "shortfall_deg": None}
    angles = np.array([signed_angle(goal, -n) for n in normals])
    low, high = float(np.min(angles)), float(np.max(angles))
    # Distinct press directions, to one degree. This is the quantity that is 1 on a
    # planar face and is what bounds the authority.
    distinct = len(np.unique(np.round(angles, 0)))
    # The goal direction is phi = 0 by construction. The shortfall is how far outside
    # the reachable interval it lies; zero when the team can aim exactly at the goal.
    shortfall = 0.0 if low <= 0.0 <= high else min(abs(low), abs(high))
    return {
        "members": int(len(normals)),
        "distinct": int(distinct),
        "low_deg": low,
        "high_deg": high,
        "half_width_deg": 0.5 * (high - low),
        "shortfall_deg": shortfall,
    }


def run_seed(config: dict, seed: int, max_frames: int) -> dict:
    env = SimulationEnvironment(config, seed=seed)
    cargo = env.cargoes[0]
    task = env.tasks[cargo.object_id]
    goal = np.asarray(task.direction, dtype=float).reshape(2)
    threshold = float(env.controller.params.push_side_threshold)

    frames: list[dict] = []
    for _ in range(int(max_frames)):
        env.step()
        if not env.controller.phase_monitor.reached(Phase.TRANSPORT):
            continue
        if env.controller.phase_monitor.reached(Phase.HOLD):
            break

        # The push set, and each member's own observed normal. Read from the robot's own
        # map view, which is the same quantity the press direction is taken from.
        normals = []
        for diagnostic, agent in zip(env.controller.diagnostics, env.agents):
            if not diagnostic.push_side:
                continue
            view = env.controller._views.get(agent.agent_id)
            if view is None or len(view) == 0:
                continue
            nearest = env.controller._nearest_index(view, agent.position)
            if nearest is not None:
                normals.append(view.normals[nearest])
        cone = reachable_cone(np.asarray(normals) if normals else np.zeros((0, 2)), goal)
        frames.append(cone)

    summary = env.summary()
    entry = next(iter(summary["cargoes"].values()))
    m = entry["g500"]["metrics"]
    j = float(m["J"])
    direction_error = float(m["direction_error_deg"])
    cross_track = float(m["max_cross_track"])

    live = [f for f in frames if f["members"] > 0]
    return {
        "seed": seed,
        "success": bool(entry["g500"]["success"]),
        "J": j,
        "direction_error_deg": direction_error,
        "max_cross_track": cross_track,
        # The identity the gate rests on.
        "identity_prediction": j * math.sin(math.radians(direction_error)),
        # What an absolute 0.15 m gate demands of the direction, at this episode's J.
        "implied_direction_gate_deg": (
            math.degrees(math.asin(min(1.0, CROSS_TRACK_GATE / j))) if j > CROSS_TRACK_GATE else 90.0
        ),
        "transport_frames": len(frames),
        "frames_with_push_set": len(live),
        "push_members_mean": float(np.mean([f["members"] for f in live])) if live else 0.0,
        "distinct_normals_mean": float(np.mean([f["distinct"] for f in live])) if live else 0.0,
        "distinct_normals_max": int(max((f["distinct"] for f in live), default=0)),
        "single_normal_fraction": (
            float(np.mean([f["distinct"] == 1 for f in live])) if live else None
        ),
        "cone_half_width_mean_deg": float(np.mean([f["half_width_deg"] for f in live])) if live else 0.0,
        "cone_half_width_p95_deg": (
            float(np.quantile([f["half_width_deg"] for f in live], 0.95)) if live else 0.0
        ),
        "goal_outside_cone_fraction": (
            float(np.mean([f["shortfall_deg"] > 0.0 for f in live])) if live else None
        ),
        "shortfall_mean_deg": float(np.mean([f["shortfall_deg"] for f in live])) if live else 0.0,
        "shortfall_max_deg": float(max((f["shortfall_deg"] for f in live), default=0.0)),
        "push_side_threshold": threshold,
        "membership_cone_deg": math.degrees(math.acos(threshold)),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--config", default=BASE_CONFIG)
    parser.add_argument("--seeds", default="0..11")
    parser.add_argument("--max-frames", type=int, default=3000)
    parser.add_argument("--out", default="docs/results/t3")
    args = parser.parse_args()

    config = load_yaml(args.config)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    rows = []
    for seed in parse_seeds(args.seeds):
        row = run_seed(config, seed, args.max_frames)
        rows.append(row)
        print(
            f"seed {seed:2d}  J={row['J']:.3f}  dir={row['direction_error_deg']:5.2f}deg  "
            f"cross={row['max_cross_track']:.4f}  pred={row['identity_prediction']:.4f}  "
            f"implied_gate={row['implied_direction_gate_deg']:5.2f}deg  "
            f"distinct_n={row['distinct_normals_mean']:.2f}  "
            f"cone+-{row['cone_half_width_mean_deg']:5.2f}deg  "
            f"single_normal={row['single_normal_fraction']}",
            flush=True,
        )

    cross = np.array([r["max_cross_track"] for r in rows])
    pred = np.array([r["identity_prediction"] for r in rows])
    correlation = float(np.corrcoef(cross, pred)[0, 1])

    report = {
        "experiment": "T3 lateral authority: the reachable normal cone",
        "config": args.config,
        "cross_track_gate_m": CROSS_TRACK_GATE,
        "identity": {
            "form": "max cross-track = J * sin(direction error)",
            "correlation": correlation,
            "mean_absolute_residual_m": float(np.mean(np.abs(cross - pred))),
        },
        "direction_error_deg_mean": float(np.mean([r["direction_error_deg"] for r in rows])),
        "implied_direction_gate_deg_mean": float(
            np.mean([r["implied_direction_gate_deg"] for r in rows])
        ),
        "distinct_normals_mean": float(np.mean([r["distinct_normals_mean"] for r in rows])),
        "single_normal_fraction_mean": float(
            np.mean([r["single_normal_fraction"] for r in rows if r["single_normal_fraction"] is not None])
        ),
        "cone_half_width_mean_deg": float(np.mean([r["cone_half_width_mean_deg"] for r in rows])),
        "goal_outside_cone_fraction_mean": float(
            np.mean([r["goal_outside_cone_fraction"] for r in rows if r["goal_outside_cone_fraction"] is not None])
        ),
        "runs": rows,
    }
    (out / "lateral_authority.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    print()
    print("=" * 78)
    print(f"identity  max cross-track = J sin(direction error)   correlation {correlation:.4f}")
    print(f"          mean |residual| {report['identity']['mean_absolute_residual_m']:.4f} m")
    print(f"measured  direction error mean        {report['direction_error_deg_mean']:.2f} deg")
    print(f"gate      0.15 m implies, at these J  {report['implied_direction_gate_deg_mean']:.2f} deg")
    print(f"cone      distinct press directions   {report['distinct_normals_mean']:.2f} on average")
    print(f"          arc on a single normal      {report['single_normal_fraction_mean']:.3f} of frames")
    print(f"          reachable half-width        {report['cone_half_width_mean_deg']:.2f} deg")
    print(f"          goal outside the cone       {report['goal_outside_cone_fraction_mean']:.3f} of frames")
    print("=" * 78)
    print(f"wrote {out / 'lateral_authority.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
