"""Render the Theorem 1 supplement to LaTeX.

Same source as the Word build (:mod:`theorem1_document`), so the .tex and the
.docx cannot state different mathematics.  This file is the canonical typeset
source; build it with any TeX engine, e.g.

    latexmk -pdf -interaction=nonstopmode theory/supplement/theorem1_supplement.tex
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import theorem1_document as content  # noqa: E402


HERE = Path(__file__).resolve().parent
OUT = HERE / "theorem1_supplement.tex"
PDF_OUT = HERE / "DBACT_Theorem1_Proofs_and_Supporting_Results.pdf"
CERT = HERE.parent / "certificates" / "analytic_constants.json"

PREAMBLE = r"""% Generated by theory/supplement/render_latex.py -- do not edit by hand.
% The prose and every formula live in theory/supplement/theorem1_document.py,
% which also drives the Word build, so the two outputs cannot diverge.
\documentclass[11pt,a4paper]{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb,amsthm}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{ragged2e}
\usepackage[table]{xcolor}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage[most]{tcolorbox}
\usepackage[hidelinks]{hyperref}

\definecolor{dbnavy}{HTML}{17324D}
\definecolor{dbblue}{HTML}{2A6F97}
\definecolor{dbmuted}{HTML}{5C6B78}
\definecolor{dbpale}{HTML}{EAF2F8}
\definecolor{dbcalloutbg}{HTML}{F4F8FB}

\titleformat{\section}{\normalfont\Large\bfseries\color{dbnavy}}{\thesection}{0.6em}{}
\titleformat{\subsection}{\normalfont\large\bfseries\color{dbblue}}{\thesubsection}{0.6em}{}
\titleformat{\subsubsection}{\normalfont\normalsize\bfseries\color{dbnavy}}{}{0em}{}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\footnotesize\color{dbmuted}@@running_left@@}
\fancyhead[R]{\footnotesize\color{dbmuted}@@running_right@@}
\fancyfoot[L]{\footnotesize\color{dbmuted}Baseline HEAD @@head12@@}
\fancyfoot[R]{\footnotesize\color{dbmuted}\thepage}
\renewcommand{\headrulewidth}{0.4pt}

\newtcolorbox{dbcallout}[1]{%
  breakable, enhanced, colback=dbcalloutbg, colframe=dbcalloutbg,
  boxrule=0pt, leftrule=2.5pt, sharp corners,
  borderline west={2.5pt}{0pt}{dbblue},
  left=9pt, right=9pt, top=7pt, bottom=7pt,
  title={#1}, coltitle=dbblue, colbacktitle=dbcalloutbg,
  fonttitle=\footnotesize\bfseries, titlerule=0pt, attach title to upper=\par\smallskip
}

\setlength{\parindent}{0pt}
\setlength{\parskip}{0.55em}

\begin{document}

\begin{titlepage}
\centering
\vspace*{3cm}
{\color{dbblue}\large\bfseries @@kicker@@}\par\medskip
{\color{dbnavy}\Huge\bfseries @@title@@}\par\bigskip
{\color{dbmuted}\large @@subtitle@@}\par
\vspace{1.5cm}
\rowcolors{1}{dbpale}{dbpale}
\begin{tabular}{>{\bfseries\color{dbnavy}}p{3cm} p{10cm}}
@@status_rows@@
\end{tabular}
\vspace{1.5cm}

{\color{dbblue}\footnotesize\bfseries @@callout_head@@}\par\medskip
{\color{dbnavy}\bfseries @@callout_body@@}
\end{titlepage}

\tableofcontents
\newpage
"""


def esc(text: str) -> str:
    """Escape the LaTeX specials that can appear in our prose."""
    for a, b in (("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"),
                 ("$", "\\$"), ("#", "\\#"), ("_", "\\_"),
                 ("{", "\\{"), ("}", "\\}"), ("~", "\\textasciitilde{}"),
                 ("^", "\\textasciicircum{}")):
        text = text.replace(a, b)
    return text


def rich(text: str) -> str:
    """Body text with ``$...$`` kept as maths and ``\\emph{}`` preserved."""
    out = []
    i = 0
    n = len(text)
    buf: list[str] = []
    while i < n:
        if text[i] == "$":
            end = text.find("$", i + 1)
            if end < 0:
                buf.append(text[i])
                i += 1
                continue
            out.append(esc("".join(buf)))
            buf = []
            out.append("$" + text[i + 1:end] + "$")
            i = end + 1
        elif text.startswith("\\emph{", i):
            end = text.find("}", i)
            if end < 0:
                buf.append(text[i])
                i += 1
                continue
            out.append(esc("".join(buf)))
            buf = []
            out.append("\\emph{" + esc(text[i + 6:end]) + "}")
            i = end + 1
        else:
            buf.append(text[i])
            i += 1
    out.append(esc("".join(buf)))
    return "".join(out)


_COLSPEC = {
    "status": ">{\\bfseries}p{2.4cm} p{11cm}",
    "assumptions": ">{\\bfseries}p{0.9cm} p{8.4cm} p{4.6cm}",
    "limits": "p{3.1cm} p{2.6cm} p{8.2cm}",
    "ledger": "l r l l",
    "wolfram": "p{2.4cm} p{6.2cm} p{2.3cm} p{2.6cm}",
}


def render_table(kind: str, rows: list[list[str]]) -> str:
    spec = _COLSPEC[kind]
    header = kind in ("assumptions", "limits", "ledger", "wolfram")
    lines = ["\\begin{center}", "\\small",
             "\\begin{longtable}{" + spec + "}", "\\toprule"]
    body = rows
    if header:
        lines.append(" & ".join("\\textbf{" + rich(c) + "}" for c in rows[0]) + " \\\\")
        lines.append("\\midrule")
        lines.append("\\endhead")
        body = rows[1:]
    for row in body:
        lines.append(" & ".join(rich(c) for c in row) + " \\\\")
    lines += ["\\bottomrule", "\\end{longtable}", "\\end{center}"]
    return "\n".join(lines)


def render(blocks: list[tuple]) -> str:
    out: list[str] = []
    for block in blocks:
        kind, args = block[0], block[1:]
        if kind == "h1":
            out.append("\\section{" + rich(args[0]) + "}")
        elif kind == "h2":
            out.append("\\subsection{" + rich(args[0]) + "}")
        elif kind == "h3":
            out.append("\\subsubsection{" + rich(args[0]) + "}")
        elif kind in ("para", "lead"):
            out.append(rich(args[0]))
        elif kind == "eq":
            latex, tag = args[0], (args[1] if len(args) > 1 else None)
            if tag:
                out.append("\\begin{equation}\n" + latex
                           + "\n\\tag{" + esc(tag) + "}\n\\end{equation}")
            else:
                out.append("\\[\n" + latex + "\n\\]")
        elif kind == "chain":
            rows = []
            for latex, why in args[0]:
                rows.append("  " + latex + " && \\text{\\footnotesize "
                            + rich(why).replace("$", "$") + "} \\\\")
            out.append("\\begin{align*}\n" + "\n".join(rows) + "\n\\end{align*}")
        elif kind == "bullets":
            items = "\n".join("  \\item " + rich(x) for x in args[0])
            out.append("\\begin{itemize}[leftmargin=1.2em,itemsep=2pt]\n"
                       + items + "\n\\end{itemize}")
        elif kind == "callout":
            out.append("\\begin{dbcallout}{" + rich(args[0]) + "}\n"
                       + rich(args[1]) + "\n\\end{dbcallout}")
        elif kind == "table":
            out.append(render_table(args[0], args[1]))
        elif kind == "pagebreak":
            out.append("\\newpage")
        else:  # pragma: no cover - guards against a new block kind
            raise ValueError(f"unhandled block kind {kind!r}")
    return "\n\n".join(out)


def compile_pdf() -> bool:
    """Typeset the generated .tex, if a TeX engine is on PATH."""
    import shutil
    import subprocess
    import tempfile

    engine = shutil.which("tectonic")
    if engine is None:
        print("no tectonic on PATH; wrote the .tex only")
        return False
    with tempfile.TemporaryDirectory() as tmp:
        result = subprocess.run(
            [engine, "-X", "compile", str(OUT), "--outdir", tmp],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            tail = (result.stderr or result.stdout).strip().splitlines()[-15:]
            raise RuntimeError("tectonic failed:\n  " + "\n  ".join(tail))
        produced = Path(tmp) / (OUT.stem + ".pdf")
        PDF_OUT.write_bytes(produced.read_bytes())
    print(f"wrote {PDF_OUT}")
    return True


def build() -> None:
    cert = json.loads(CERT.read_text(encoding="utf-8"))
    status = "\n".join(f"{esc(k)} & {esc(v)} \\\\" for k, v in content.STATUS_ROWS)
    head = PREAMBLE
    for key, value in {
        "kicker": esc(content.KICKER),
        "title": esc(content.TITLE),
        "subtitle": esc(content.SUBTITLE),
        "status_rows": status,
        "callout_head": esc(content.CALLOUT_HEAD),
        "callout_body": esc(content.CALLOUT_BODY),
        "running_left": esc(content.RUNNING_LEFT),
        "running_right": esc(content.RUNNING_RIGHT),
        "head12": esc(content.HEAD[:12]),
    }.items():
        head = head.replace("@@" + key + "@@", value)
    OUT.write_text(head + "\n" + render(content.document(cert))
                   + "\n\n\\end{document}\n", encoding="utf-8")
    print(f"wrote {OUT}")
    compile_pdf()


if __name__ == "__main__":
    build()
